// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7RVnkuk4nuA9LbSJpWXy8TmP5lhiuMjc',
    appId: '1:376497531154:web:462736964fe89528b12bcb',
    messagingSenderId: '376497531154',
    projectId: 'e-commercetestapp',
    authDomain: 'e-commercetestapp.firebaseapp.com',
    storageBucket: 'e-commercetestapp.firebasestorage.app',
    measurementId: 'G-C1080140QF',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWy66BngkENZGuBCC8FACqyb8gTSldbo0',
    appId: '1:376497531154:ios:cd146da98a56946bb12bcb',
    messagingSenderId: '376497531154',
    projectId: 'e-commercetestapp',
    storageBucket: 'e-commercetestapp.firebasestorage.app',
    iosBundleId: 'com.example.buyhive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7RVnkuk4nuA9LbSJpWXy8TmP5lhiuMjc',
    appId: '1:376497531154:web:04fbf755f13317f6b12bcb',
    messagingSenderId: '376497531154',
    projectId: 'e-commercetestapp',
    authDomain: 'e-commercetestapp.firebaseapp.com',
    storageBucket: 'e-commercetestapp.firebasestorage.app',
    measurementId: 'G-6Y1E313E6Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKMjghKYydO2_ebhVWmh4TdbNE6AwrTtc',
    appId: '1:376497531154:android:7121b761c9f1f845b12bcb',
    messagingSenderId: '376497531154',
    projectId: 'e-commercetestapp',
    storageBucket: 'e-commercetestapp.firebasestorage.app',
  );

}